name: Оксана Коновалова
bio: Психолог
footer_title: ИП Коновалова Оксана Валерьевна ИНН 645293010504
description: Сайт психолога Коноваловой Оксаны

picture: assets/images/profile.jpg
url: https://oksana-konovalova.com

social-media: true
#instagram: myinstagram
telegram: Konovalova_Oksana
whatsapp: 79053810566
email: ttm.help.ru@gmail.com

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: normal

# do you want to display an about section? true or false
about: true

# do you want to display a skills section? true or false
skills: true
skills-list:
    - Юридический психолог (ФГБОУ ВПО СГЮА)
    - Когнитивно-поведенческая психотерапия (АНО ДПО АПС)
    - Психологическое консультирование родителей (ФГБНУ ПИРАО)
    - Библиотерапия в работе с детьми (ФГБНУ ПИРАО)
    - Professional Coach (IICA ICF ICF)
    - Professional coaching of groups and companies (IICA ICF ICF)
    - НЛП-практик
    - 'EFT Emotional Freedom Technique: Hair Pulling & Skin Picking'
    - Irvin Yalom and the Art of Psychotherapy (Newpsy education)
    - ACT in Action by Steven C.Hayes (Newpsy education)

offers: true
offers-list:
    - Первичная консультация 8 000 рублей (длительность 55 минут)
    - Консультирование 32 000 рублей за блок из 4 консультаций (1 консультация 55 минут)
    - Участие в клубе с обратной связью 15 000 рублей за 4 недели

# do you want to display a projects section? true or false
projects: false

# add your projects here
project-list:
    QuizKnit:
        name: QauizKnit
        description: AI powered web application that generates a quiz based on user provided text. Users can share the quiz using a custom url and also test their knowledge by exploring quizzes created by other people.
        url: https://quizknit.com

# do you want to display the theme attribution? true or false
footer: true

# Enable animations? true or false
animation: true

gems:
    - jekyll-seo-tag

exclude: [README.md, Gemfile, Gemfile.lock, _site, Rakefile, vendor]
