name: Оксана Коновалова
bio: Психолог
footer_title: ИП Коновалова Оксана Валерьевна ИНН 645293010504
description: Сайт психолога Коноваловой Оксаны

picture: assets/images/profile.jpg
url: https://oksana-konovalova.com

social-media: true
#instagram: myinstagram
telegram: Konovalova_Oksana
whatsapp: 79053810566
email: ttm.help.ru@gmail.com

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: normal

# do you want to display an about section? true or false
about: true

# do you want to display a skills section? true or false
skills: true
skills-list:
    - Юридический психолог (Саратовская государственная юридическая академия)
    - Клинический психолог (Институт психотерапии и клинической психологии)
    - Когнитивно-поведенческая психотерапия (Академия профессиональных стандартов)
    - Тренер навыков ДБТ (Международная академия научной психологии)

offers: true
offers-list:
    - Первичная консультация 8 500 рублей (длительность 55 минут)
    - Консультирование 34 000 рублей за блок из 4 консультаций (1 консультация длительностью 55 минут)
    - Участие в клубе с обратной связью 19 000 рублей за 4 недели

# do you want to display a projects section? true or false
projects: false

# add your projects here
project-list:
    QuizKnit:
        name: QauizKnit
        description: AI powered web application that generates a quiz based on user provided text. Users can share the quiz using a custom url and also test their knowledge by exploring quizzes created by other people.
        url: https://quizknit.com

# do you want to display the theme attribution? true or false
footer: true

# Enable animations? true or false
animation: true

gems:
    - jekyll-seo-tag

exclude: [README.md, Gemfile, Gemfile.lock, _site, Rakefile, vendor]
